//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eattofit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cartao
    {
        public int IdCartao { get; set; }
        public string Bandeira { get; set; }
        public string ImagemUrl { get; set; }
        public Nullable<int> IdFornecedor { get; set; }
    
        public virtual Fornecedor Fornecedor { get; set; }
    }
}
