//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eattofit
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.Nota = new HashSet<Nota>();
        }
    
        public int IdPedido { get; set; }
        [Display(Name = "Quantidade")]
        public Nullable<int> QantidadePedido { get; set; }
        public Nullable<int> IdProduto { get; set; }
        [Display(Name = "Valor")]
        public Nullable<decimal> ValorPedido { get; set; }
        public Nullable<int> IdNota { get; set; }
        public Nullable<int> IdPedidoMobile { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Nota> Nota { get; set; }
        public virtual Produto Produto { get; set; }
        public virtual Nota Nota1 { get; set; }
    }
}
