//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace eattofit
{
    using System;
    using System.Collections.Generic;
    
    public partial class Produto
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Produto()
        {
            this.Pedido = new HashSet<Pedido>();
        }
    
        public int IdProduto { get; set; }

        [Required(ErrorMessage = "Obrigatório informar Nome")]
        [Display(Name = "Nome Produto")]
        public string NomeProduto { get; set; }

        [Required(ErrorMessage = "Obrigatório informar Descrição")]
        [Display(Name = "Descrição")]
        public string DescricaoProduto { get; set; }


        [Display(Name = "Valor Produto")]
        [DataType(DataType.Currency)]
        [DisplayFormat(DataFormatString = "{0:C2}", ApplyFormatInEditMode = true)]
        public Nullable<decimal> ValorProduto { get; set; }

        [Display(Name = "Categoria")]
        public Nullable<int> IdCategoria { get; set; }

        public Nullable<int> IdFornecedor { get; set; }

        [Display(Name = "Imagem")]
        [DataType(DataType.ImageUrl)]
        public string Url { get; set; }
    
        public virtual Categoria Categoria { get; set; }
        public virtual Fornecedor Fornecedor { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pedido> Pedido { get; set; }
    }
}
